enum class GlyphId : uint8_t {
    Placeholder = 0,
    VolumeUp,
    VolumeMute,
    Trash,
    Notes,
    MediaPlayReverse,
    MediaPlay,
    MediaRecord,
    MediaRewind,
    MediaFastForward,
    MediaStop,
    MediaPause,
    MediaRecordOutline,
    AdjustContrast,
    DeleteOutline,
    TabsOutline,
    Bluetooth,
    Book,
    Exec,
    OpenBook,
    SdCard,
    Owl,
    Crab,
    Film,
    Camera,
    ArrowLeftThick,
    Location,
    ArrowRightThick,
    Map,
    At,

    BatteryCharge,
    BatteryFull,
    BatteryHigh,
    BatteryMid,
    BatteryLow,
    Bell,
    ArrowSync,
    Backspace,
    Document,
    DocumentText,
    Filter,
    Eye,
    Flash,
    FolderOpen,
    Folder,
    HeartFullOutline,
    Home,
    Keyboard,
    LockClosed,
    LockOpen,
    Mail,
    Microphone,
    Message,
    Plus,
    Pencil,
    Refresh,

    WeatherCloudy,
    WeatherDownpour,
    WeatherSunny,
    WeatherStormy,
    WeatherShower,
    WeatherPartlySunny,
    WeatherSnow,
    Minus,
    World,
    ZoomIn,
    ZoomOut,
    WiFiOutline,
    WiFi,
    Cog,
    CogOutline,
    Power,
    PowerOutline,
    Spanner,
    Starburst,
    StarburstOutline,
    ThumbsUp,
    Warning,
    Ticket,
    Thermometer,
    Star,
    ThMenu,
    ThSmallOutline,
    ThMenuOutline,
    ThLargeOutline,
    Time,
    User,
    BusinessCard,
    Brush,
    Calculator,
    Calendar,
    Picture,
};

static constexpr GlyphId ASCII_TO_GLYPH[94] = {
    /* ! */ GlyphId::VolumeUp,
    /* " */ GlyphId::VolumeMute,
    /* # */ GlyphId::Trash,
    /* $ */ GlyphId::Notes,
    /* % */ GlyphId::MediaPlayReverse,
    /* & */ GlyphId::MediaPlay,
    /* ' */ GlyphId::MediaRecord,
    /* ( */ GlyphId::MediaRewind,
    /* ) */ GlyphId::MediaFastForward,
    /* * */ GlyphId::MediaStop,
    /* + */ GlyphId::MediaPause,
    /* , */ GlyphId::MediaRecordOutline,
    /* - */ GlyphId::AdjustContrast,
    /* . */ GlyphId::DeleteOutline,
    /* / */ GlyphId::TabsOutline,
    /* 0 */ GlyphId::Bluetooth,
    /* 1 */ GlyphId::Book,
    /* 2 */ GlyphId::Exec,
    /* 3 */ GlyphId::OpenBook,
    /* 4 */ GlyphId::SdCard,
    /* 5 */ GlyphId::Owl,
    /* 6 */ GlyphId::Crab,
    /* 7 */ GlyphId::Placeholder,
    /* 8 */ GlyphId::Placeholder,
    /* 9 */ GlyphId::Placeholder,
    /* : */ GlyphId::Film,
    /* ; */ GlyphId::Camera,
    /* < */ GlyphId::ArrowLeftThick,
    /* = */ GlyphId::Location,
    /* > */ GlyphId::ArrowRightThick,
    /* ? */ GlyphId::Map,
    /* @ */ GlyphId::At,
    /* A */ GlyphId::BatteryCharge,
    /* B */ GlyphId::BatteryFull,
    /* C */ GlyphId::BatteryHigh,
    /* D */ GlyphId::BatteryMid,
    /* E */ GlyphId::BatteryLow,
    /* F */ GlyphId::Bell,
    /* G */ GlyphId::ArrowSync,
    /* H */ GlyphId::Backspace,
    /* I */ GlyphId::Document,
    /* J */ GlyphId::DocumentText,
    /* K */ GlyphId::Filter,
    /* L */ GlyphId::Eye,
    /* M */ GlyphId::Flash,
    /* N */ GlyphId::FolderOpen,
    /* O */ GlyphId::Folder,
    /* P */ GlyphId::HeartFullOutline,
    /* Q */ GlyphId::Home,
    /* R */ GlyphId::Keyboard,
    /* S */ GlyphId::LockClosed,
    /* T */ GlyphId::LockOpen,
    /* U */ GlyphId::Mail,
    /* V */ GlyphId::Microphone,
    /* W */ GlyphId::Message,
    /* X */ GlyphId::Plus,
    /* Y */ GlyphId::Pencil,
    /* Z */ GlyphId::Refresh,
    /* [ */ GlyphId::WeatherCloudy,
    /* \ */ GlyphId::WeatherDownpour,
    /* ] */ GlyphId::WeatherSunny,
    /* ^ */ GlyphId::WeatherStormy,
    /* _ */ GlyphId::WeatherShower,
    /* ` */ GlyphId::WeatherPartlySunny,
    /* a */ GlyphId::WeatherSnow,
    /* b */ GlyphId::Minus,
    /* c */ GlyphId::World,
    /* d */ GlyphId::ZoomIn,
    /* e */ GlyphId::ZoomOut,
    /* f */ GlyphId::WiFiOutline,
    /* g */ GlyphId::WiFi,
    /* h */ GlyphId::Cog,
    /* i */ GlyphId::CogOutline,
    /* j */ GlyphId::Power,
    /* k */ GlyphId::PowerOutline,
    /* l */ GlyphId::Spanner,
    /* m */ GlyphId::Starburst,
    /* n */ GlyphId::StarburstOutline,
    /* o */ GlyphId::ThumbsUp,
    /* p */ GlyphId::Warning,
    /* q */ GlyphId::Ticket,
    /* r */ GlyphId::Thermometer,
    /* s */ GlyphId::Star,
    /* t */ GlyphId::ThMenu,
    /* u */ GlyphId::ThSmallOutline,
    /* v */ GlyphId::ThMenuOutline,
    /* w */ GlyphId::ThLargeOutline,
    /* x */ GlyphId::Time,
    /* y */ GlyphId::User,
    /* z */ GlyphId::BusinessCard,
    /* { */ GlyphId::Brush,
    /* | */ GlyphId::Calculator,
    /* } */ GlyphId::Calendar,
    /* ~ */ GlyphId::Picture,
};

constexpr GlyphId GetGlyph(char c) {
    return ASCII_TO_GLYPH[static_cast<uint8_t>(c) - '!'];
}
