#!/bin/bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env"
EXAMPLE_FILE="$ROOT/.env.example"
OUT_FILE="$ROOT/src/secrets_config.h"

if [[ -f "$ENV_FILE" ]]; then
  SOURCE_FILE="$ENV_FILE"
elif [[ -f "$EXAMPLE_FILE" ]]; then
  SOURCE_FILE="$EXAMPLE_FILE"
else
  printf 'Missing %s and %s\n' "$ENV_FILE" "$EXAMPLE_FILE" >&2
  exit 1
fi

set -a
# shellcheck disable=SC1090
source "$SOURCE_FILE"
set +a

cpp_string() {
  local value="${1:-}"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '"%s"' "$value"
}

write_define() {
  local name="$1"
  local value="${2:-}"
  printf '#define %s ' "$name"
  cpp_string "$value"
  printf '\n'
}

{
  printf '#ifndef SECRETS_CONFIG_H\n'
  printf '#define SECRETS_CONFIG_H\n\n'
  printf '// Generated by tools/generate-secrets-header.sh. Do not edit.\n\n'
  write_define SECRET_WIFI_SSID "${WIFI_SSID:-}"
  write_define SECRET_WIFI_PASSWORD "${WIFI_PASSWORD:-}"
  write_define SECRET_WIFI_DISPLAY_NAME "${WIFI_DISPLAY_NAME:-Saved network}"
  printf '\n'
  write_define SECRET_CONTACT_NAME "${CONTACT_NAME:-Your Name}"
  write_define SECRET_CONTACT_PROFESSION "${CONTACT_PROFESSION:-Your Profession}"
  write_define SECRET_CONTACT_TELEGRAM_URL "${CONTACT_TELEGRAM_URL:-https://t.me/user}"
  write_define SECRET_CONTACT_EMAIL_URL "${CONTACT_EMAIL_URL:-mailto:user@mail.co}"
  write_define SECRET_CONTACT_PHONE_URL "${CONTACT_PHONE_URL:-tel:+10000000000}"
  write_define SECRET_CONTACT_LINKEDIN_URL "${CONTACT_LINKEDIN_URL:-https://lnkd.in/user}"
  write_define SECRET_CONTACT_WHATSAPP_URL "${CONTACT_WHATSAPP_URL:-https://wa.me/1000000}"
  printf '\n'
  write_define SECRET_WEATHER_LATITUDE "${WEATHER_LATITUDE:-0.0}"
  write_define SECRET_WEATHER_LONGITUDE "${WEATHER_LONGITUDE:--0.0}"
  printf '\n'
  write_define SECRET_AI_API_BASE_URL "${AI_API_BASE_URL:-}"
  write_define SECRET_AI_API_KEY "${AI_API_KEY:-}"
  write_define SECRET_AI_MODEL_PRIMARY "${AI_MODEL_PRIMARY:-}"
  write_define SECRET_AI_MODEL_SECONDARY "${AI_MODEL_SECONDARY:-}"
  printf '\n#endif\n'
} >"$OUT_FILE"
